---
name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: v18.1.0
          cache: npm

      - run: |
          npm install

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
