---
# Heavily inspired by ganache's release workflow: https://github.com/trufflesuite/ganache/blob/develop/.github/workflows/release.yml
name: Release SDK

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: v18.1.0
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Download latest API doc
        run: npm run fetchAPITypes

      # Will increase package.json without running commit hooks, without creating a git tag
      - name: Bump version in package.json
        run: npm version "${{ github.event.inputs.release_type }}" --commit-hooks=false --git-tag-version=false


      - name: Get package version
        id: get-version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"

      - name: Set SonarQube project version
        run: sed -i 's/^sonar.projectVersion=.*$/sonar.projectVersion=${{ env.PACKAGE_VERSION }}/g' sonar-project.properties

      - name: Update documentation (gitbook infura, ...)
        run: echo "update documentation"

      - name: Grant execute permissions to shell script
        run: chmod +x ./scripts/releaseGit.sh

      - name: Setup git info / add & commit / create tag
        run: ./scripts/releaseGit.sh ${{ env.PACKAGE_VERSION }}

      - name: Release 🚀
        run: npx semantic-release --debug
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org'

      - name: Release NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org
          access: 'public'
      
      #- name: Merge changes back to dev
      #  run: ./scripts/merge-dev.sh