---
name: Release

on:
  issue_comment:                                     
    types: [created]

jobs:
  if: |
    (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/release'))
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v18.1.0
          cache: npm
      - name: Install packages
        run: npm ci --ignore-scripts
      - name: Run unit tests
        run: npm test
      - name: Run E2E tests
        run: npm test:e2e
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: v18.1.0
          cache: npm

      - name: Install packages
        run: npm ci
      - name: Publish with Verdaccio
        uses: verdaccio/github-actions/publish@master
        with:
          args: -d
      # - name: Set up auth for npm publish
      #   run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Release to npm
      #   run: npm publish
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # TODO add documentation update
      # TODO update version info & git push
      # TODO add git release?
