---
name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2
        with:
          node-version: v18.1.0
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Lint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check

      - name: Unit tests
        run: npm run test
        env:
          RPC_URL: ${{ secrets.RPC_URL }}

      - name: e2e tests
        run: npm run test:e2e
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
          RPC_URL: ${{ secrets.RPC_URL }}
      
      - name: Audit
        run: npm audit

      - name: Publish on Verdaccio
        uses: verdaccio/github-actions/publish@master
        with:
          args: -d

      # uncomment to publish publicly
      # - name: Publish on NPM
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      #     npm publish --registry https://registry.npmjs.org/
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # bump version manually (e.g., before creating the tag)
      # - name: Setup git info
      #   run: |
      #     git config --global user.email "johannbich@gmail.com"
      #     git config --global user.name "kalote"

      # - name: Bump npm version
      #   run: npm version ${{ github.ref_name }} -m "bump version to %s"

      # - name: Commit version 
      #   run: |
      #     git status
      #     git push
